### ISSUE TITLE
mio::make_mmap_sink cannot use... in VS2015 

### ISSUE THREAD

**Issue by aijyo** [mandreyel/mio#30]
Just as the title. I have try to run example code in test.cpp, and failed...

follow is the scenes:
![image](https://user-images.githubusercontent.com/7956449/48057447-0a3cf300-e1ef-11e8-916a-6f7fe12e7966.png)

**Comment by aijyo** [comment]
I fix the problem by modify 2 point:
first add a param to the sync invork:
![image](https://user-images.githubusercontent.com/7956449/48107313-220d8900-e27a-11e8-88ff-5989942b49c7.png)

second move the sync impl form mmap.ipp to the mmap.h:
![image](https://user-images.githubusercontent.com/7956449/48107343-3fdaee00-e27a-11e8-8804-e5b01bcdfa55.png)

**Comment by russpowers** [comment]
This fixed my issue on Visual Studio 2017, thanks!  The `conditional_sync` thing seems to be a problem in this library, and the need to move `sync` into mmap.h is probably something wrong with the VC++ compiler, as usual 😁

**Comment by mandreyel** [comment]
@aijyo Thank you for reporting this! My apologies, I actually had a follow up commit that fixes this issue but forgot to push it. It should be fixed now.

**Comment by aijyo** [comment]
> @aijyo Thank you for reporting this! My apologies, I actually had a follow up commit that fixes this issue but forgot to push it. It should be fixed now.

Thanks for you reply and effort .
Actually, I don’t know why it’s wrong...

**Comment by mandreyel** [comment]
@aijyo It's still not working as expected?

**Comment by aijyo** [comment]
> @aijyo It's still not working as expected?

I have read about you latest commit, and test again....
 Sadly, It's still not working, your  commit just fixed the first error but the second is still(which I  move the sync impl form mmap.ipp to the mmap.h  then fixed):
![image](https://user-images.githubusercontent.com/7956449/48125469-b9de9780-e2b9-11e8-82e8-a8d19760aa57.png)

**Comment by russpowers** [comment]
VC++ is notorious for crap SFINAE support, especially when you use std::enable_if as a template parameter instead of a return value.  I think the forward template declaration is messing it up in this case.  The error I was getting was a resolution error, it can't deduce the second template argument (the enable_if).

**Comment by mandreyel** [comment]
@russpowers Oh, hmm, that's good to know. I'm not very familiar with VC++. Maybe it's enough to just move the `enable_if` to `conditional_sync`'s return type? Unfortunately I don't have access to a Windows machine right now, so can't verify. I'd really appreciate either of your help!

**Comment by mandreyel** [comment]
I pushed an attempt now. @aijyo Could you please test it now?

**Comment by russpowers** [comment]
Oh, the SFINAE problem isn't with `conditional_sync`, it's `sync`, which is forward declared.  @aijyo reported two fixes, the first was making the `sync` function body inline.  I guess separating the declaration from the implementation is messing up VC++'s fragile SFINAE system.

**Comment by mandreyel** [comment]
@russpowers To be honest, I'd prefer not to inline that function if at all possible, but if nothing else works that'll have to do.

**Comment by russpowers** [comment]
Yeah, that's what I figured.  Maybe `sync` could be inline and just be a simple call to a private function that doesn't use SFINAE?

**Comment by mandreyel** [comment]
@russpowers Hmm, that could work. In my previous attempt I moved `conditional_sync`'s implementation to the `.ipp` file. Any chance that fixes it? If not, I'll do as you suggested.

**Comment by russpowers** [comment]
The problem happens when calling `sync` from anywhere, not just in `conditional_sync`.  Let me try copying what you did from `conditional_sync` over to `sync` and see how it works.

**Comment by aijyo** [comment]
> The problem happens when calling `sync` from anywhere, not just in `conditional_sync`. Let me try copying what you did from `conditional_sync` over to `sync` and see how it works.

modify mmap.h::sync function as the picture show, will fix the problem
https://user-images.githubusercontent.com/7956449/48107343-3fdaee00-e27a-11e8-8804-e5b01bcdfa55.png

**Comment by mandreyel** [comment]
@russpowers I see. I assumed it might have simply been a matter of what definition VC++ saw first. I'll go your route then, with a private member function.

**Comment by russpowers** [comment]
Hold up, I think the return value enable_if might work.  Give me a few
minutes..

**Comment by aijyo** [comment]
okay~ I'm use vs2015 test it

**Comment by mandreyel** [comment]
@aijyo I saw your suggestion, pardon me for not reacting. I'm looking for a solution that does not involve inlining the `sync` method. @russpowers' solution seems like a good compromise. I pushed the changes now. Could you please test whether it works now?

**Comment by mandreyel** [comment]
@russpowers Oh, that would be interesting! I pushed your previous suggestion (inline `sync` and have the a private member implement the actual logic), but I'd welcome removing the above indirection.

**Comment by mandreyel** [comment]
@russpowers Awesome, I'll amend my last commit in favor of this solution. Thank you for testing it!

**Comment by aijyo** [comment]
> > @aijyo I saw your suggestion, pardon me for not reacting. I'm looking for a solution that does not involve inlining the `sync` method. @russpowers' solution seems like a good compromise. I pushed the changes now. Could you please test whether it works now?
> 
> > @aijyo I saw your suggestion, pardon me for not reacting. I'm looking for a solution that does not involve inlining the `sync` method. @russpowers' solution seems like a good compromise. I pushed the changes now. Could you please test whether it works now?
> 
> I
> 
> > @aijyo I saw your suggestion, pardon me for not reacting. I'm looking for a solution that does not involve inlining the `sync` method. @russpowers' solution seems like a good compromise. I pushed the changes now. Could you please test whether it works now?
> 
> ...I cann't find a vs2015 now, I can test tomorrow...

Test on vs2017 everthing is okay now, but .. vs2015 not test, I'll try tomorrow

**Comment by russpowers** [comment]
@mandreyel Thanks for fixing it! 😄

**Comment by mandreyel** [comment]
@russpowers @aijyo Thank you for your collaboration, much appreciated! :beers:

@russpowers Just to make sure, could you please verify that [this](https://github.com/mandreyel/mio/commit/45e5fcde9736a36011b74684f8f605581707ae3a) is what you meant?

**Comment by russpowers** [comment]
Yes, exactly!  I just tested the latest version from master and it's working.

**Comment by mandreyel** [comment]
@russpowers Awesome! Thanks again :)

I'm leaving this open just in case it's not a sufficient fix for VS 2015, @aijyo.

**Comment by aijyo** [comment]
> @russpowers Awesome! Thanks again :)
> 
> I'm leaving this open just in case it's not a sufficient fix for VS 2015, @aijyo 
Tommorow I‘ll test on vs2015

**Comment by mandreyel** [comment]
@aijyo Thank you so much for taking the time to check it!
